### PR TITLE
Added big conv example

### PR DESCRIPTION
**Pull request by dillonhuff**
@David-Durst let me know if you see anything odd about this example. If it looks good I'll send in the other examples.

### CODE REVIEW

**Comment by David-Durst** [comment]
Looks normal to me. I'm going to run this through pnr later today or tomorrow. Did you run this through c simulation?

Could you add a _0 to the end of the name, like big_conv2d_2073600_0.v? I added that to the naming scheme as sometimes now I'll create multiple versions with the same throughput (though I'm not doing that in this example).

**Comment by dillonhuff** [comment]
Just got C simulation running and it passed. I changed the name too. I'll run the other throughputs tonight or tomorrow afternoon.

**Comment by David-Durst** [comment]
great, thank you!

**Comment by dillonhuff** [comment]
@David-Durst so because of size and divisibility issues we cannot do 4 and 8 pixels per clock, (we ran into the same divisibility issues for 64 x 64 inputs).

I have added the 2 pixel per clock example though.

**Comment by David-Durst** [comment]
@David-Durst thank you!

**Pull request merged**
